defaults:
    - override hydra/launcher: joblib
    - override hydra/sweeper: optuna
    - override hydra/sweeper/sampler: tpe
    - override hydra/job_logging: colorlog
    - override hydra/hydra_logging: colorlog

hydra:
    sweeper:
        sampler:
            seed: 123
        direction: maximize
        study_name: 20S3060
        storage: null
        n_trials: 100
        n_jobs: 1

        search_space:
            n_layers:
                type: int
                low: 1
                high: 10
                step: 1
            embedding_dim:
                type: int
                low: 20
                high: 200
                step: 50
            dropout:
                type: float
                low: 0.1
                high: 0.8
                step: 0.1
#            pos_weight:
#                type: int
#                low: 0
#                high: 5000
#                step: 100

n_layers: 1
embedding_dim: 10
dropout: 0.5
#pos_weight: 1000
save_graph: false

